# -*- coding: utf-8 -*-
"""Conheça o Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

#exercício de DataFrames no Pandas

import pandas as pd

# Criar o DataFrame com os dados fornecidos
cidades_br = pd.DataFrame({
    'Cidade': ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte', 'Porto Alegre', 'Curitiba'],
    'Estado': ['SP', 'RJ', 'MG', 'RS', 'PR'],
    'População (milhões)': [12.3, 6.7, 2.5, 1.5, 1.9],
    'Capital': [True, True, True, True, True]
})
Cidades = pd.DataFrame(cidades_br)
print(Cidades)

# Exibir as 3 primeiras linhas
print(Cidades.head(3))

# Exibir 2 linhas aleatórias
print(Cidades.sample(2))

# Seleção de colunas
print(Cidades[['Cidade']])
print(Cidades[['Estado', 'População (milhões)']])

# Adicionando coluna Área
Cidades['Area (km²)'] = [1521, 1200, 331, 496, 435]
print(Cidades)

# Alterar Capital para False em Porto Alegre e Curitiba
Cidades.loc[Cidades['Cidade'].isin(['Porto Alegre', 'Curitiba']), 'Capital'] = False
print(Cidades)

# Renomear colunas
Cidades = Cidades.rename(columns={
    'Cidade': 'Nome da Cidade',
    'Estado': 'UF',
    'População (milhões)': 'Habitantes (M)',
    'Capital': 'É Capital',
    'Area (km²)': 'Tamanho (km²)'
})
print(Cidades)

# Descrição estatística
print(Cidades.describe())

# Filtrar cidades com população > 2.0
print(Cidades[Cidades['Habitantes (M)'] > 2.0])

# Remover coluna Tamanho
Cidades = Cidades.drop(columns=['Tamanho (km²)'])
print(Cidades)

# Primeira linha
print(Cidades.iloc[0:1])

# Linhas de 1 a 3
print(Cidades.iloc[1:4])

# Apenas UF e Habitantes (M) das linhas 0 e 4
print(Cidades.iloc[0:5:4, [1,2]])